In [6]:
doc_ls = ['바나나 사과 포도 포도',
'사과 포도',
'포도 바나나',
'짜장면 짬뽕 탕수욕',
'볶음밥 탕수욕',
'짜장면 짬뽕',
'라면 스시',
'스시',
'가츠동 스시 소바',
'된장찌개 김치찌개 김치',
'김치 된장',
'비빔밥 김치'
]
import pandas as pd
import numpy as np
from collections import defaultdict

In [11]:
class LSA :
    def __init__(self, doc_ls, topic_num):
        self.doc_ls = doc_ls
        self.topic_num = topic_num
        self.term2idx, self.idx2term = self.toIdxDict(' '.join(doc_ls).split())
        self.doc2idx, self.idx2doc = self.toIdxDict(doc_ls)
        self.tdm = self.TDM(doc_ls)
        self.U, self.s, self.VT = self.SVD(self.tdm)
        pass

    def TDM(self, doc_ls):
       
        
        return tdm        
        pass

    def TopicModeling(self) :
        for i in range(topic_num):
            score=self.U[:,i:i+1]
            
        pass

    # 문서를 입력했을 때 문서 벡터 반환
    def GetDocVector(self, doc):
        pass
    # 단어-문서 벡터 행렬 생성
    def TermDocVectorMatrix(self, u, s, vt):
        pass
    # 단어 벡터 행렬에서 단어 간 코사인 유사도 측정하여 행렬형태로 반환
    def TermSimilarityMatrix(self, term_vec_matrix):
        pass

    def GetTermSimilarity(self, term1, term2):
        document_ls=[i.split()  for i in doc_ls]
        token_dict=defaultdict(lambda:len(token_dict))
        for document in document_ls:
            for token in document:
                token_dict[token]
        index_token=sorted((value,key) for key,value in token_dict.items())
        token_in_order=[tup[1] for tup in index_token]
        n_word = len(token_dict) 
        n_doc = len(document_ls)
        TDM=pd.DataFrame(np.zeros((n_doc,n_word)),columns=token_in_order,index=['문서1','문서2','문서3','문서4','문서5','문서6','문서7','문서8','문서9','문서10','문서11','문서12'],dtype=int)
        
        for i,document in enumerate(document_ls):
            for token in document:
                token_location=token_dict[token]
                TDM.iloc[i,token_location]+=1
                tdm=TDM.T
        
        U, s, VT = np.linalg.svd(tdm)
        term_vec_matrix=np.matrix(U[:, :topic_num])* np.diag(s[:topic_num])
        term1= term_vec_matrix[token_in_order.index(term1)]
        term2= term_vec_matrix[token_in_order.index(term2)]
        nominator=np.dot(term1, term2.T)
        denominator=np.linalg.norm(term1)*np.linalg.norm(term2)
        return nominator/denominator
        pass

    def GetDocSimilarity(self, doc1, doc2):
        document_ls=[i.split()  for i in doc_ls]
        token_dict=defaultdict(lambda:len(token_dict))
        for document in document_ls:
            for token in document:
                token_dict[token]
        index_token=sorted((value,key) for key,value in token_dict.items())
        token_in_order=[tup[1] for tup in index_token]
        n_word = len(token_dict) 
        n_doc = len(document_ls)
        TDM=pd.DataFrame(np.zeros((n_doc,n_word)),columns=token_in_order,index=['문서1','문서2','문서3','문서4','문서5','문서6','문서7','문서8','문서9','문서10','문서11','문서12'],dtype=int)
        for i,document in enumerate(document_ls):
            for token in document:
                token_location=token_dict[token]
                TDM.iloc[i,token_location]+=1
                tdm=TDM.T
        U, s, VT = np.linalg.svd(tdm)       
        doc_vec_matrix=np.dot(s,np.matrix(VT[:topic_num,:])).T
        doc1=doc_vec_matrix[token_in_order.index(doc1)]
        doc2=doc_vec_matrix[token_in_order.index(doc2)]
        nominator=np.dot(doc1, doc2.T)
        denominator=np.linalg.norm(doc1)*np.linalg.norm(doc2)
        return nominator/denominator
        pass

    def GetTermDocSimilarity(self, term1, doc1):
        term1= term_vec_matrix[token_in_order.index(term1)]
        doc1= doc_vec_matrix[token_in_order.index(doc1)]
        nominator=np.dot(term1, doc1.T)
        denominator=np.linalg.norm(term1)*np.linalg.norm(doc1)
        return nominator/denominator
        pass
lsa = LSA(doc_ls, 3)
lsa.TopicModeling()
lsa.GetTermSimilarity('사과','바나나')
lsa.GetTermSimilarity('사과','짜장면')
lsa.GetDocSimilarity('사과 포도', '포도 바나나')
lsa.GetDocSimilarity('사과 포도', '라면 스시')
lsa.GetTermDocSimilarity('사과', '포도 바나나')
lsa.GetTermDocSimilarity('사과', '김치 된장')

ValueError: '사과 포도' is not in list

In [28]:
import pandas as pd
import numpy as np
from collections import defaultdict
document_ls=[i.split()  for i in doc_ls]
token_dict=defaultdict(lambda:len(token_dict))
for document in document_ls:
    for token in document:
        token_dict[token]
index_token=sorted((value,key) for key,value in token_dict.items())
token_in_order=[tup[1] for tup in index_token]
n_word = len(token_dict) 
n_doc = len(document_ls)
TDM=pd.DataFrame(np.zeros((n_doc,n_word)),columns=token_in_order,index=['문서1','문서2','문서3','문서4','문서5','문서6','문서7','문서8','문서9','문서10','문서11','문서12'],dtype=int)
for i,document in enumerate(document_ls):
    for token in document:
        token_location=token_dict[token]
        TDM.iloc[i,token_location]+=1  
tdm=TDM.T        
U, s, VT = np.linalg.svd(tdm)
from sklearn. import randomizedsvd
from ..utils.extmath import randomized_svd, safe_sparse_dot, svd_flip
U,s,VT=randomized_svd(x,n_component=15,n_iter=5,random_state=None)

In [35]:
term1='사과'
term2='바나나'
term_vec_matrix=np.matrix(U[:, :12])* np.diag(s[:])
term1= term_vec_matrix[token_in_order.index(term1)]
term2= term_vec_matrix[token_in_order.index(term2)]
nominator=np.dot(term1, term2.T)
denominator=np.linalg.norm(term1)*np.linalg.norm(term2)
nominator/denominator

matrix([[0.5]])

In [45]:
term1='사과'
doc1='포도 바나나'
term_vec_matrix=np.matrix(U[:, :topic_num])* np.diag(s[:topic_num])
doc_vec_matrix=np.diag(s[:topic_num])*np.matrix(VT[:topic_num,:])
term1= term_vec_matrix[token_in_order.index(term1)]
doc1= doc_vec_matrix[doc_ls.index(doc1)]
nominator=np.dot(term1, doc1.T)
denominator=np.linalg.norm(term1)*np.linalg.norm(doc1)
nominator/denominator

matrix([[3.4606787e-17]])

In [87]:
import numpy as np
import scipy.sparse as sp
from scipy.sparse.linalg import svds

from sklearn.utils.extmath import randomized_svd, safe_sparse_dot, svd_flip
import pandas as pd
import numpy as np
from collections import defaultdict
document_ls=[i.split()  for i in doc_ls]
token_dict=defaultdict(lambda:len(token_dict))
for document in document_ls:
    for token in document:
        token_dict[token]
index_token=sorted((value,key) for key,value in token_dict.items())
token_in_order=[tup[1] for tup in index_token]
n_word = len(token_dict) 
n_doc = len(document_ls)
TDM=pd.DataFrame(np.zeros((n_doc,n_word)),columns=token_in_order,index=['문서1','문서2','문서3','문서4','문서5','문서6','문서7','문서8','문서9','문서10','문서11','문서12'],dtype=int)
for i,document in enumerate(document_ls):
    for token in document:
        token_location=token_dict[token]
        TDM.iloc[i,token_location]+=1  
tdm=TDM.T        
U,s,VT=randomized_svd(tdm,n_components=15,n_iter=5,random_state=None)

doc1='사과 포도'
doc2='포도 바나나'
doc_vec_matrix=np.diag(s[:topic_num])*np.matrix(VT[:topic_num,:])
doc1=doc_vec_matrix[doc_ls.index(doc1)]
doc2=doc_vec_matrix[doc_ls.index(doc2)]
nominator=np.dot(doc1, doc2.T)
denominator=np.linalg.norm(doc1)*np.linalg.norm(doc2)
nominator/denominator

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [62]:
s[:3]

array([3.        , 2.18890106, 2.10100299])

In [61]:
np.diag(s[:3])

array([[3.        , 0.        , 0.        ],
       [0.        , 2.18890106, 0.        ],
       [0.        , 0.        , 2.10100299]])

In [65]:
doc_vec_matrix

matrix([[-2.44948974, -1.22474487, -1.22474487,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , -1.70833729, -0.61202476,
         -1.22404953,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        , -1.48563346,
         -1.05050149, -1.05050149]])

In [66]:
nominator

matrix([[0.]])