In [11]:
word_ls = ['원숭이','바나나','사과','사과']

In [9]:
from collections import defaultdict
import numpy as np

In [19]:
#one hot encoding= 단어는 연산 못하니까,단어 갯수 n개일 때 n차원 array에 해당 단어 1찍어서 단어 표현
def one_hot_encode(word_Is):
    word2idx_dic=defaultdict(lambda:len(word2idx_dic))
#단어별 인덱스 만들기, 중복되는 단어의 인덱스는 똑같게 한개 만들려고, 새로 단어 추가하면 걔도 인덱스 생김
    for word in word_ls:
        word2idx_dic[word]
        
    n_unique_words=len(word2idx_dic)
#nxn matrix 셋팅
    one_hot_vectors=np.zeros((len(word_ls),n_unique_words))
    
    for i,word in enumerate(word_ls):
        index=word2idx_dic[word]
        one_hot_vectors[i,index]+=1
    return one_hot_vectors 
one_hot_encode(word_ls)


TypeError: 'tuple' object is not callable

In [20]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [22]:
value = array(word_ls)

In [23]:
print(value)

['원숭이' '바나나' '사과' '사과']


In [24]:
label=LabelEncoder()

In [39]:
intt=label.fit_transform(value)
print(intt)#ㄱㄴㄷ순

[2 0 1 1]


In [38]:
onehot_enc=OneHotEncoder(sparse=False)
int_enc=intt.reshape(len(intt),1)
onehot_enc=onehot_enc.fit_transform(int_enc)
print(int_enc)
print(onehot_enc)

[[2]
 [0]
 [1]
 [1]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
